language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib pandas jinja2
  # coverage packages are elsewhere
  #- conda install --yes -c python-coveralls nose-cov
  - pip install nose easydev --upgrade
  - pip install coveralls -v
  - pip install colormap 

# # command to run tests, e.g. python setup.py test
script:
  - python setup.py install
  - python setup.py nosetests --with-coverage --cover-package reports

after_success:
  coveralls

